### ISSUE TITLE
NIHCC Chest X-ray dataset

### ISSUE THREAD

**Issue by jlagarespo** [NIC-VICOROB/COVID19#4]
Review [this dataset](https://www.kaggle.com/neilturley/nihcc-chest-xray), could be potentially interesting.

**Comment by sergivalverde** [comment]
definitely. This dataset is a subset of the NIHCC dataset from here: 

https://www.nih.gov/news-events/news-releases/nih-clinical-center-provides-one-largest-publicly-available-chest-x-ray-datasets-scientific-community

We added it to the list of potential datasets.
